name: bloc_vgv_todoapp
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: 3.0.4

dependencies:
  # bloc: ^8.0.3
  cloud_firestore: ^3.4.0
  equatable: ^2.0.3
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutterfire_ui: ^0.4.2+3
  google_sign_in: ^5.4.0
  google_sign_in_mocks: ^0.2.1
  intl: ^0.17.0
  tuple: ^2.0.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
