name: bloc_vgv_todoapp
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: 3.0.4

dependencies:
  auto_route: ^4.2.1
  bloc:
  cloud_firestore:
  equatable:
  firebase_auth:
  firebase_core:
  flow_builder:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  flutterfire_ui:
  google_fonts:
  google_sign_in:
  google_sign_in_mocks:
  intl:
  tuple:

dev_dependencies:
  auto_route_generator: ^4.2.0
  bloc_test:
  build_runner:
  flutter_test:
    sdk: flutter
  mocktail:
  very_good_analysis:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
