name: firestore_repository
description: Dart package which manages the firestore domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  authentication_repository:
    path: ../authentication_repository
  cloud_firestore:
  firebase_core:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
