// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqs-c7vo4xVY2M1Vbcr_BY9J4qEXULZKE',
    appId: '1:885272001477:web:b322875de79dca5aa6a9ac',
    messagingSenderId: '885272001477',
    projectId: 'bloc-test-july2022',
    authDomain: 'bloc-test-july2022.firebaseapp.com',
    storageBucket: 'bloc-test-july2022.appspot.com',
    measurementId: 'G-FCRH4KRX3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsC0JBXM8eWL1KcmFMeUrUMRWi4I8NO04',
    appId: '1:885272001477:android:0fc804d64dbc540da6a9ac',
    messagingSenderId: '885272001477',
    projectId: 'bloc-test-july2022',
    storageBucket: 'bloc-test-july2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsM7VlBw5e-_dh_h3rZYR3drLarPfU-uw',
    appId: '1:885272001477:ios:4fbacdc8e0f7dcbea6a9ac',
    messagingSenderId: '885272001477',
    projectId: 'bloc-test-july2022',
    storageBucket: 'bloc-test-july2022.appspot.com',
    iosClientId:
        '885272001477-grueiqj04t7mbvl054060rhjv52ii98e.apps.googleusercontent.com',
    iosBundleId: 'com.gdgapps.anton.bloc_vgv_todoapp.bloc-vgv-todoapp',
  );
}
